direction: down

users: {
  shape: sql_table
  id: UUID {constraint: primary_key}
  username: TEXT {constraint: unique}
  email: TEXT {constraint: unique}
  password_hash: TEXT
  is_verified: BOOL
  created_at: DATETIME
  updated_at: DATETIME
}

library_entries: {
  shape: sql_table
  id: UUID {constraint: primary_key}
  title: TEXT
  user_id: UUID {constraint: foreign_key}
  media_id: TEXT
  source_id: UUID {constraint: foreign_key}
  image_src: TEXT
  media_type: TEXT
  status: TEXT
  public_rating: REAL
  personal_rating: REAL
  released_at: DATETIME
  created_at: DATETIME
  updated_at: DATETIME
}

source_integrations: {
	shape: sql_table
	id: UUID {constraint: primary_key}
	is_active: BOOL
	integration_type: TEXT
	user_id: UUID {constraint: foreign_key}
	config_json: TEXT
}

ai_integrations: {
	shape: sql_table
	id: UUID {constraint: primary_key}
	is_active: BOOL
	integration_type: TEXT
	user_id: UUID {constraint: foreign_key}
	config_json: TEXT
}

alias_mappings: {
	shape: sql_table
	id: UUID {constraint: primary_key}
	user_id: UUID {constraint: foreign_key}
	alias: TEXT
	expansion: TEXT
}

content_nodes: {
	shape: sql_table
	id: UUID {constraint: primary_key}
	title: TEXT
	link: TEXT
	order_index: INT
	library_entry_id: UUID {constraint: foreign_key}
}

tags: {
	shape: sql_table
	id: UUID {constraint: primary_key}
	user_id: UUID {constraint: foreign_key}
	value: TEXT
	weight: TEXT
}

library_entry_tags: {
	shape: sql_table
	library_entry_id: UUID {constraint: [primary_key; foreign_key]}
	tag_id: UUID {constraint: [primary_key; foreign_key]}
}

collections: {
	shape: sql_table
	id: UUID {constraint: primary_key}
	name: TEXT
	created_at: DATETIME
	updated_at: DATETIME
}

collection_entries: {
	shape: sql_table
	id: UUID {constraint: primary_key}
	collection_id: UUID {constraint: foreign_key}
	library_entry_id: UUID {constraint: foreign_key}
}

otp_codes: {
	shape: sql_table
	id: UUID {constraint: primary_key}
	user_id: UUID {constraint: foreign_key}
	otp_code: TEXT
	otp_code_expiration_date: DATETIME
	created_at: DATETIME
}

library_entries.user_id -> users.id
library_entries.source_id -> source_integrations.id
source_integrations.user_id -> users.id
ai_integrations.user_id -> users.id
alias_mappings.user_id -> users.id
content_nodes.library_entry_id -> library_entries.id
tags.user_id -> users.id
library_entry_tags.library_entry_id -> library_entries.id
library_entry_tags.tag_id -> tags.id
collection_entries.collection_id -> collections.id
collection_entries.library_entry_id -> library_entries.id
otp_codes.user_id -> users.id
