services:
  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile.prod
    restart: unless-stopped
    volumes:
      - sqlite_data:/app/packages/server/data
    environment:
      DATABASE_URL: sqlite:///app/packages/server/data/db.sqlite
      NODE_ENV: production

  web-client:
    build:
      context: .
      dockerfile: packages/web-client/Dockerfile.prod
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server
volumes:
  sqlite_data:
