services:
  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    command: ["bun", "--hot", "index.ts"]
    ports:
      - "8080:8080"
    volumes:
      - ./packages/server:/app/packages/server
    environment:
      DATABASE_URL: sqlite:///app/packages/server/data/db.sqlite

  web-client:
    build:
      context: .
      dockerfile: packages/web-client/Dockerfile
    command: ["bun", "--hot", "src/index.tsx"]
    ports:
      - "3000:3000"
    volumes:
      - ./packages/web-client:/app/packages/web-client
    depends_on:
      - server
